### ISSUE TITLE
Can't send notification

### ISSUE THREAD

**Issue by lafritte57** [OctoPrint/OctoPrint-Pushbullet#13]
Hi there,

Since the 0.1.7 release, the plugin can't send notification to my devices.
Even if I try the test message, I've got the popup 

> Test message could not be sent
> Test message could not be sent to Pushbullet, check settings.

I tried to clean-up my delivered token and regenerate a new one (that I used on other app and which works on it) but I've got the same [issue](http://imgur.com/mug3708).

Today I upgrade the plugin to 0.1.8 but it's exactly the same case.

I'm on Octoprint 1.3.2 and the log file return that : 

> 2017-04-12 18:17:42,958 - octoprint.plugins.octobullet - ERROR - Error while instantiating PushBullet
> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 214, in _create_sender
>     bullet = pushbullet.PushBullet(token)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 29, in __init__
>     self.refresh()
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 288, in refresh
>     self._load_devices()
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 42, in _load_devices
>     resp_dict = self._get_data(self.DEVICES_URL)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 32, in _get_data
>     resp = self._session.get(url)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
>     return self.request('GET', url, **kwargs)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
>     raise SSLError(e, request=request)
> SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

I already checked my config file and the write token is fill in it.

Any way to resolve it ?

Thanks

**Comment by foosel** [comment]
I ran into the same issue. You are still running OctoPi 0.12 I assume, or at least a python version older than 2.7.9? There appears to be an issue with pushbullets API (or rather its SSL termination) and the older python versions (eg 2.7.3 is the best available for wheezy which OctoPi 0.12 is still based on).

Try this, that is what fixed it (and the warning about SSL on start of OctoPrint) for me:

    sudo apt-get update
    sudo apt-get install libffi-dev
    source ~/oprint/bin/activate
    pip install requests[security]

Small heads up: this will take a bit. It will download a bunch of security libraries, at least one of which needs to be compiled. It took a couple of minutes on a Pi2. After that, restart OctoPrint. This should fix the issue.

**Comment by lafritte57** [comment]
So fast and efficient!  

Thanks a lot, I just had to follow your instructions and it works again, as you said!

I'll close this issue and maybe it could be useful for others...

**Comment by foosel** [comment]
I also added a note about this to the README
