### ISSUE TITLE
Error on sending notification to channels

### ISSUE THREAD

**Issue by lampi87** [OctoPrint/OctoPrint-Pushbullet#14]
Hello,

I try to send notifications to a channel, but I always get this exception:
```
2017-04-24 10:58:20,235 - octoprint.plugins.octobullet - ERROR - Error while instantiating PushBullet
Traceback (most recent call last):
  File "/home/user/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 219, in _create_sender
    for channel_obj in self._bullet.channels:
AttributeError: 'NoneType' object has no attribute 'channels'
```

Any ideas?

Thx,
Alexander

**Comment by foosel** [comment]
Currently not, I'll try to find the time to look into it though. In the meantime, if anyone else manages before me, any feedback (or pull requests) welcome :)

**Comment by SgtSiff** [comment]
Any progress on this? Cheers!

**Comment by foosel** [comment]
No, too much else to do. Patches welcome. I cannot even reproduce this.

**Comment by lampi87** [comment]
With newest version of octoprint it works for me out of the box

**Comment by SgtSiff** [comment]
I'm thinking this was never an issue, I was getting the same error as above, running the latest version of octoprint.

To make it work click save after entering the API key, then enter the channel name, click save again and it works fine!

**Comment by ociotec** [comment]
Thanks a lot SgtSiff, that solved my problem!!!

**Comment by foosel** [comment]
Found it, will be fixed in the next release.
