### ISSUE TITLE
[Request] Send picture on a set interval in minutes

### ISSUE THREAD

**Issue by prahjister** [OctoPrint/OctoPrint-Pushbullet#15]
Can you include an option to send a picture on a set interval in minutes? This would allow ability to watch a print and make sure not failing.

**Comment by foosel** [comment]
Sorry, I don't have the time to add something like this. PRs welcome though.

**Comment by tsh-xx** [comment]
I will take a stab at trying to implement this (assuming I can cut-paste most of what's needed).

**Comment by foosel** [comment]
@tsh-xx sounds great! 👍

**Comment by prahjister** [comment]
Fantastic. Ty

**Comment by prahjister** [comment]
Thank you....This is fantastic.
