### ISSUE TITLE
Up for adoption

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint-Pushbullet#24]
I have my hands way too full with OctoPrint's maintenance to give this plugin the attention it needs. Hence I'm looking for a new maintainer to adopt it.

**Comment by SkullKill** [comment]
hi, any reason why the devel branch was not merged into the master branch ? is it because more testing is required ?

**Comment by foosel** [comment]
No time.

**Comment by scottrini** [comment]
@foosel I'd be happy to take this over.  I just recently noticed it broke on my octoprint instances and fixed it, so I'd gladly push those changes and work on updating it for py3 support.

**Comment by foosel** [comment]
You've got the job!

**Comment by SkullKill** [comment]
> so I'd gladly push those changes and work on updating it for py3 support.

hi scottrini, i can't see your fork for this with the fix.

**Comment by scottrini** [comment]
@SkullKill Sorry, I neglected creating my fork.  I finally created my own and I just have the one tiny fix I've made.  I haven't started on the py3 support yet.

**Comment by foosel** [comment]
@scottrini FYI, you also have a pending invite for maintainer access to *this* repository...

![image](https://user-images.githubusercontent.com/83657/79841682-12bfc400-83b8-11ea-8f45-1dd31f4ea322.png)

**Comment by scottrini** [comment]
@foosel Could you actually resend it somehow?  I tried to accept, but apparently the invitation link is expired.

**Comment by foosel** [comment]
Just resent it.

**Comment by foosel** [comment]
@scottrini I'll leave it to you to close this issue :)
