### ISSUE TITLE
Not compatible with Python 3.8.1

### ISSUE THREAD

**Issue by Steeven9** [OctoPrint/OctoPrint-Pushbullet#25]
Plugin install fine via GitHub URL but then doesn't load up on boot.

[octoprint.log](https://github.com/OctoPrint/OctoPrint-Pushbullet/files/4154032/octoprint.log)

**Comment by foosel** [comment]
Yes. That's correct. As you can see on the plugin listing it's also not marked as compatible for Python 3+:

![image](https://user-images.githubusercontent.com/83657/73755280-1606c480-4766-11ea-92a0-f50dc6521772.png)

and as thus marked as incompatible in the plugin repository browser within OctoPrint too.

I no longer have time to maintain this plugin, don't use it myself anymore and have been looking for a maintainer for a while, see #24. Unless someone else takes over the wheel, this plugin won't get ported to Py3.

**Comment by Steeven9** [comment]
Aww what a shame... it was a quite useful plugin that will be missed.

**Comment by foosel** [comment]
If it will really be missed I guess someone will adopt it, but that hasn't happened in over a year now, which tells me it ain't that important to the community 🤷‍♀️

**Comment by ubergeekseven** [comment]
OH no! what are you using as a replacement for this? Have you just stopped getting notifications? The test output does work when you press the test button, I just thought I was doing something wrong.

**Comment by Steeven9** [comment]
> OH no! what are you using as a replacement for this? Have you just stopped getting notifications? The test output does work when you press the test button, I just thought I was doing something wrong.

I switched to the Telegram bot plugin, it works pretty well

**Comment by h4nc** [comment]
Pushbullet stopped working after updating to Octoprint 1.4.1 because of the [deprecated flask.ext imports](https://github.com/OctoPrint/OctoPrint/releases/tag/1.4.1).

@foosel I understand that this plugin currently isn't maintained, but I can't tell if it's a lot work to fix this. So that's the reason why it would be great to know if this will be fixed?

If not it would be good to know how to delete the plugin. Currently it doesn't show up as installed in the plugins section, but I think the plugin will try to boot everytime Octoprint is restarted. 
So if it can't be used any more it would be great to remove it completely.

**Comment by foosel** [comment]
It's not a lot of work and boils down to simply replacing some imports. If someone sends me a PR that takes care of that I'm happy to push a release with that merged, however I'm not going to invest any time on this plugin as long as there's not even this amount of interest reflected from the community to keep it working.

**Comment by scottrini** [comment]
This has been on my radar to finally get back to and update, but I just haven't had the time recently.  I might have some time at the end of the week, I'll block off some time on my calendar to take a look.

**Comment by foosel** [comment]
I clearly need a vacation, I totally forgot this even got adopted 😅🤦‍♀️🤪

**Comment by h4nc** [comment]
@scottrini That would be great, thanks!

@foosel The plugin shows up in the logs, so it is installed. However it doesn't show up as installed in the plugin section any more, which is why there is no button deinstall the plugin. Is there another way to delete the plugin in this case?

**Comment by foosel** [comment]
Yes, from the command line. See https://community.octoprint.org/t/i-installed-a-broken-plugin-how-do-i-uninstall-it-again/217

Or try starting in safe mode, might still show up then maybe.

**Comment by scottrini** [comment]
This is now compatible with Python3.
