### ISSUE TITLE
It disappeared and it doesn't install on Octoprint 1.4.1/1.4.2

### ISSUE THREAD

**Issue by spanzetta** [OctoPrint/OctoPrint-Pushbullet#28]
After the update to 1.4.1/1.4.2 (from 1.4.0) the plugin disappeared and if I try to install again.. even if the setup seems to be fine.. at the end after the reboot the plugin is again not present 
Pls check 
Thanks

**Comment by spanzetta** [comment]
any chance to get it fixed?

**Comment by scottrini** [comment]
Sure, it's just a matter of finding some time to dig in.  I'm sure this is a matter of changing up some import, just like the python3 update for this plugin, but I'll have to make some time to get to it.  I took this over, as the plugin had been up for adoption because it doesn't get much use anymore.  I still use it, so I volunteered.  I should have some time to look at it sometime this weekend.

**Comment by spanzetta** [comment]
dear Scottrini
thanks a lot for the reply..
It would be really nice if you could fix it.. I really like this plugin ;-)
Thanks again

**Comment by lepetitcreole** [comment]
Hi!
I saw this error in my logs : "ImportError: No module named ext.login".

To fix it :
Edit file /home/pi/oprint/lib/python2.7/site-packages/octoprint_octobullet/__init__.py
Line 16, replace  flask.ext.login by  flask_login.
=> from flask_login import current_user
Save it and restart the server.

**Comment by scottrini** [comment]
@lepetitcreole yes, good call!  I was actually just looking into this and it took me the longest to go that far back in the logs.  I'm going to get this pushed in a few minutes and bump/tag it.

**Comment by lepetitcreole** [comment]
Great, thanks for your job!

**Comment by scottrini** [comment]
Alright, I just pushed and tagged 0.1.11.

**Comment by spanzetta** [comment]
Dear Scottrini
I saw that you created 0.1.11.. but if I try to install it from OctoPrint plugin manager it still mention 0.1.10 (the problematic one)..
Is that normal? 
Do you know when 0.1.11 will be available to download?
Thanks in advance

**Comment by spanzetta** [comment]
I have installed it again anyway and I just noticed that even if it still say 0.1.10.. now the plugin works (it contains the fix)
Thanks a lot..
I am now closing this issue..
