### ISSUE TITLE
No notifications coming through, even though the test works

### ISSUE THREAD

**Issue by jeffeb3** [OctoPrint/OctoPrint-Pushbullet#9]
I haven't been using my printer a lot, but I started again this weekend, and updated to the latest versions. 

But I haven't been getting pushbullet notifications. I tried a test, and it worked fine. Maybe whatever triggers the notification is broken?

PB Plugin v0.1.6
OctoPrint v 1.2.16

**Comment by Akex2** [comment]
yes me too
i re install the older version and it work fine

**Comment by foosel** [comment]
@Akex2 The older version of the plugin or an older version of OctoPrint (if so which one?)

**Comment by foosel** [comment]
Also, sorry @jeffeb3, the notification for this ticket managed to get buried.

**Comment by foosel** [comment]
Never mind. I found an embarrassingly stupid error. Fixed version 0.1.7 incoming.

**Comment by jeffeb3** [comment]
@foosel No problem. I probably should have pinged again.

**Comment by foosel** [comment]
Version 0.1.7 should be out now.

**Comment by jeffeb3** [comment]
Working again. Thank you.
